image: www

variables:
 DOCKER_DRIVER: overlay2

services:
 - docker:dind

stages:
 - build

before_script:
 - docker info
 - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
 - mkdir ./www/js/
 - wget https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js -P ./www/js

build_dev:
 stage: build
 script:
  - docker build -t registry.gitlab.com/wannabee/www .
  - docker push registry.gitlab.com/wannabee/www
